<?php echo $this->render('topo.phtml'); ?>
<h1 class="h2 mb-0"><?php echo $this->translate->_('Contato') ?></h1>
<div class="alert rounded alert-success fade in margin-bottom-40">
    <h4><?php echo $this->translate->_('Sucesso!'); ?></h4>
    <?php echo $this->translate->_('Seu e-mail foi enviado com sucesso. <br/><br/>Em breve entraremos em contato.'); ?>
</div>
<?php echo $this->render('baixo.phtml'); ?>
